### ISSUE TITLE
Unable to run on ARM

### ISSUE THREAD

**Issue by ZetaPhoenix** [containous/whoami#10]
I am attempting to debug my configuration of Traefik running on a Raspberry Pi 3B+ (Docker 18.06.1-ce, go1.10.3, Raspbian GNU/Linux 9 (stretch)) and I get the following error:

`standard_init_linux.go:190: exec user process caused "exec format error"` 

Since the Traefik container will run on the ARM platform, does it make sense to make the test/debug image work on the platform as well?

**Comment by ldez** [comment]
@ZetaPhoenix Hello, the image is build with an AMD64 version, the docker hub don't allow to manage easily multi-arch for the "simple" image.

**Comment by ZetaPhoenix** [comment]
@ldez
Thanks for the response. Is there another image that could be used such as
emilevauge/whoami-arm?

**Comment by kingdevnl** [comment]
Iv'e builded an arm image. kingdevnl/whoami:arm

**Comment by smueller18** [comment]
@ldez I just implemented a multi-arch Travis build in https://github.com/CWSpear/local-persist/pull/63 . Is this an option for this project too? If yes, I would open a PR.

**Comment by ldez** [comment]
I created a small tool https://github.com/ldez/seihon, I will try to use it on this project.

**Comment by ldez** [comment]
Since [v1.4.0](https://github.com/containous/whoami/releases/tag/v1.4.0) the Docker image support ARM.

**Comment by kingdevnl** [comment]
Tho i already have gotten it to work I got a arm image on my docker hub ac

**Comment by ldez** [comment]
So now you can use our "official" image :wink:

**Comment by As9530272755** [comment]
Hello, could you please download the docker pull contained/whoami:v1.4.0 image directly and support arm64 by default? Or do you need to specify a specific image version?

**Comment by ldez** [comment]
It's a multi-arch image, you just need do run `docker pull contained/whoami:v1.4.0`
