### ISSUE TITLE
flags are not clear or not working 

### ISSUE THREAD

**Issue by PackElend** [containous/whoami#28]
Hi,
I assume 
cert: give me a certificate
key: give me a key
allow me to do https.
Does that mean it creates a certificate by itself or do I need to add the path to a local certificate?

```
curl https://localhost:32769
curl: (35) schannel: next InitializeSecurityContext failed: SEC_E_INVALID_TOKEN (0x80090308)
```

**Comment by ldez** [comment]
Hello,

the `me` in "give me" is the whoami app.

So you have to provide a cert file and a key file.

**Comment by PackElend** [comment]
I tried to start it with path on host to cert and key but didn't work.
Is the cert and key imported into the container?
How can I check if the flags were successful, beside doing curl
Can't you add a working example?

sent from a fair mobile

**Comment by PackElend** [comment]
Hello,
Any chance that someone will share a working example or can tell how I can check that the flags are processed correctly
